run = "run.sh"
# init = "init.sh"
# validate = "validate.sh"
# clean = "clean.sh"

restPort = 10080

explorePolicy = "random"

[explorePolicyParam]
  minInterval = "80ms"
  maxInterval = "3000ms"
  shellActionInterval = "5000ms"
  shellActionCommand = "echo hello $(date)"
  faultActionProbability = 0.5

