init = "init.sh"
run = "run.sh"
validate = "validate.sh"
clean = "clean.sh"
restPort = 10080
explorePolicy = "random"

notCleanIfValidationFail= "true"

[explorePolicyParam]
 minInterval = "100ms"
 maxInterval = "1000ms"

# storageType = "mongodb"
